### ISSUE TITLE
First round of feedback

### ISSUE THREAD

**Issue by bborgesr** [rstudio/pool#1]
This is the bare bones pool package. 

*Stuff that I'm still working on:*
- wrapping all (most really) DBI methods for Pool instances;
- making the Pool class robust (need to incorporate a lot more error handling and thinking of edge cases);
- implement a finalizer to check for and destroy leaked connections;
- implement a timeout mechanism to destroy leaked connections after an x amount of time and also to gradually shrink the pool size if connections have been idle for too long;
- better documentation for methods (the reason why the Travis check is failing at the moment).

*Open questions:*
- should `createPool` be a complete abstract generic? Or should it be implemented for each pooled object type (ex: `createDBIPool`, `createMongoPool`, `createBufferPool`)? The former might seem more elegant, but the latter would allow the generic to specify the actual arguments, with descriptive names, needed for the creation of each type of pool (ex: `drv` for DBI, and maybe something else like a factory function for other object types) -- instead of relying of vague argument names and `...` for everything else.

cc @jcheng5, @wch, @hadley

**Comment by hadley** [comment]
I'm going to start with the README, because I think if that was more fleshed out, it would be easier to sink my teeth into a full review:

* I think you need to provide a bit more motivation - why is it expensive to get a connection? Can you provide a compelling benchmark? I'd also recommend adding a concrete sentence about when this package is most useful, i.e. "This is particularly useful when writing shiny apps because...".  Maybe also mention it's useful in long-running processes when you don't want to leave a connection to the database open (or you want to re-connect automatically if it gets dropped).

* Generally, you should attach the DBI package, and not the backend, i.e. the sample code should look like:

    ```R
    library(DBI)
    library(pool)
    
    pool <- createPool(
      drv = RMySQL::MySQL(), 
      ...
    )
    ```

* It's great that you've shown how using a pool works just like a regular DBI connection, but I'd like to see the full interface where you check-out a connection, do something with it, and then check it back in

* Looking briefly at the code, it seems like you're forcing people to understand that this is an R6 object. I think it would be better to make this completely hidden to the user, so they can use regular R functions without understand what's going in the background.

* You might want to consider giving all functions in this package a common prefix: pool. Then you'd have `poolCreate()`, `poolCheckOut()`, `poolReturn()` etc.
