### ISSUE TITLE
Question about the necessity for a pool

### ISSUE THREAD

**Issue by dakep** [rstudio/pool#112]
The following statement in the README.md file about why to consider using a pool of DB connections makes me seriously question my understanding of how shiny apps work:

> Opening only one connection per app … cannot handle simultaneous requests (e.g. two sessions open, both querying the database at the same time);

I thought a shiny app runs in a single-threaded R process, hence there's no possibility of having two queries at the same time (one could probably share a transaction/query/statement among several reactive expressions, but that doesn't sound like a good approach).

When would there be an actual issue with only a single DB connection per R process (if ignoring the issue of a broken connection)?

Sorry for the possibly stupid question, but it's been bothering me for a few days now and I can't seem to figure it out by myself.

-- David

**Comment by hadley** [comment]
There might be multiple instances of a shiny app running on that same process, just not simultaneously. They still need their own connection to the database (so e.g. they have their own unique temporary tables).

**Comment by mmuurr** [comment]
I think this is a fair question that should be addressed perhaps with some updates to the docs, particularly the [_Why pool?_](http://rstudio.github.io/pool/articles/why-pool.html) article. Using temporary tables (i.e. statefulness associated with a connection) is a decent argument for pinning a connection to a session (or set of queries in a reactive chain), but the examples given in that article never mention such statefulness. Rather, the article _hints at_ concurrency, especially with these (context-free) statements:

> Since there is only one connection, it does not work well with multi-user apps. **[w.r.t. one-connection per app]**

> It can handle simultaneous requests, because these are always processed by different connections. **[w.r.t. one-connection per query (set)]**

I'm a huge proponent of {pool}, **especially since it'll try to re-establish broken connections**; but I don't think the current docs clearly describe the biggest advantages of using {pool} with Shiny, and possibly mislead nascent Shiny developers into thinking parallelism and/or multi-threading is somehow happening out-of-the-box (which it is not).

Are the maintainers open to an attempted restructuring of that article? I'm happy to give it a go and submit a PR. (But I also don't want to put in the time for that write-up if there's no appetite for it :-)

**Comment by hadley** [comment]
Sure, happy to consider better wording!
