### ISSUE TITLE
Question about database example

### ISSUE THREAD

**Issue by gaborcsardi** [rstudio/pool#12]
This is not an issue, just a question. Since currently R is single threaded, and the database operations are synchronous (AFAIK), the use of multiple connections to the database is quite limited in my opinion. But maybe I am missing something. Can you give an example where you actually benefit from pooling multiple connections? 

Keeping a single connection open is relatively easy, in a package I usually use sg like this:
```r
internal_data <- new.env()
dbfile <- tempfile()
db <- function() {

  ## Check if connection is still valid, open a new one if not
  if (!exists("conn", envir = internal_data) || is.null(internal_data$conn) || dbIsValid(internal_data$conn)) {
    conn <- dbConnect(SQLite(), dbfile)
    assign("conn", conn, envir = internal_data)
  }
  internal_data$conn
}
```
and then you can make queries with `dbSensQuery(db(), ...)`. You can also put the connection in a closure, if you are not writing a package.

Obviously, the `pool` package is still very useful for other use cases, but I just don't see why you would want multiple connections.

**Comment by bborgesr** [comment]
Thanks for this thoughtful question. There are a couple of things that I want to address here.

First, the main motivation for the `pool` package is so that it is harder for people to mess up when connecting to databases. Your code works very nicely but it's at a somewhat advanced coding level and lots of our users are less proficient that you seem to be. Pretending for a minute that we're not worrying about the other issues and assuming you always just need one connection (and assuming it won't time out, etc...), `DBI` is fairly straightforward. However, a recurring issue is that folks would forget to disconnect the connections they created, so they'd accumulate lots of connections. Since `pool` does that for you, it's just a lot easier to do the right thing. This was our main goal.

Second, I think you're right that most times we will only ever need one connection (which is why the default `minSize` for the pool is 1). However, it can still be useful to think of a pool for one object only. Maybe pool is not the right name here, but it gives all the traditional advantages of a pool: connection management (the first point above) and performance (you don't need to fetch a connection directly from the database all the time), in addition to other useful things (like periodically verifying that an idle connection is still valid). So essentially, it seems like you were doing this by yourself. If you are confident your code is robust (which it seems like it is), then for that particular case, you might not gain much from pool (again, apart from being maybe conceptually easier and more readable). But under the hood, in this situation, I don't think we're doing such different things.

Third, to finally answer your question. Yes, although it's rare, you can need more than one connection open at one time. Let's say you have an app and multiple sessions. One user checks out a connection from the pool, because he wants to do some complicated, maybe interactive, transaction. While he is off doing that, another user just want to get some information about the pool using `dbGetInfo(pool)`. So, we just open a second connection, get that info, and return the connection to the pool. That is faster and neater than if we had to interrupt user 1's transaction to temporarily give that connection to user 2, or wait potentially a long time for user 1 to be done with that connection. So even though R is single-threaded, if you're mid-transaction, you really don't want other people messing with your connection (especially if you need to configure it in some special way). 

As fair as synchronous database operations go, we have been talking about getting some async stuff into R, which would then make a lot of sense to incorporate into the database world. So, in the future, the number of use cases may grow.

Finally, we were careful to design `pool` such that it can be a pool for whatever object one wants (not just DBI connections), provided that a factory function and a number of methods (how to activate the object, passivate it, destroy it, etc...) are given (a vignette explaining how to implement a backend to `pool` will be coming at some point in the future). So this is a general pool. However, so far, we're only applying it to DBI connections. But there may be other pooled objects that you definitely want to have more than one open at any given time.

All that said, the greatest motivation for `pool` was to give people a very simple interface that does connection management for them (especially, prevent leaked connections) and does so fast.

Hope this helped!
