### ISSUE TITLE
error: object 'sql_join_suffix' not found

### ISSUE THREAD

**Issue by mehrlander** [rstudio/pool#121]
I'm getting this error when I try to load the package.

    > library(pool)
    Error: package or namespace load failed for ‘pool’:
     .onLoad failed in loadNamespace() for 'pool', details:
      call: get(genname, envir = envir)
      error: object 'sql_join_suffix' not found

Installation says it was successful.  I installed R 4.0.3 (had been using 4.0.0), and then reinstalled both R and RStudio to see if that would help.   However, it still gives the above error message.  Other packages seem to be loading fine.

**Comment by mkrasmus** [comment]
Hi I get this if I load tidyverse instead of dplyr prior to pool. i.e.


```
library(tidyverse)
library(shiny)
library(pool)
```

Returns the error as above. Whereas (as in the example Shiny scripts for pool):

```
library(dplyr)
library(shiny)
library(pool)
```

No error message. May help to identify which package in tidyverse is causing the issue...

**Comment by Dreznel** [comment]
I believe I have traced the source of the issue.

Long story short, the current version of `pool` is incompatible with versions of `dbplyr` prior to 2.0.0. Since `dbplyr` is a Suggested package, it's possible to use pool without `dbplyr` installed, in which case this issue doesn't manifest.

If you're getting this issue, try upgrading your `dbplyr` package to version 2.0.0 or later.

For a bit more detail,

The `pool:::.onLoad` function is registering S3 methods that it expects `dbplyr` to have. The problem is [this line.](https://github.com/rstudio/pool/blob/00fad2c2258f40759c4eddb83275dc7b50697bcb/R/zzz-hooks.R#L35)

Since the `sql_join_suffix` function didn't exist in dbplyr prior to [version 2.0.0](https://github.com/tidyverse/dbplyr/releases/tag/v2.0.0), running `library(pool)` (which in turn calls `pool:::.onLoad`) will cause an error if you have an older version of `dbplyr` currently loaded in your session.

Hope this helps!

**Comment by benhmin** [comment]
thanks so much for this help!

**Comment by hadley** [comment]
I'll bump the required version of dbplyr as part of #132.
