### ISSUE TITLE
Maximum connections exceeded in shiny app when using PostgreSQL and cannot pass in max.con via dbPool

### ISSUE THREAD

**Issue by koseri** [rstudio/pool#19]
I am running a shiny app that connects to a Postgres database and keep hitting connection limits.

> Error in postgresqlNewConnection(drv, ...) : 
>   RS-DBI driver: (cannot allocate a new connection -- maximum of 16 connections already opened)

I am therefore trying to increase the number of connections allowed. The 16 connection limit seems to be imposed by the defaults of `PostgreSQL::RPostgreSQL()` which does have a `max.con` argument. However, I cannot find the way to manipulate it with the current code. I'm assuming this is necessary because my shiny app is crashing with the above error message.

Background: I ran into this 16 connection limit previously, when connecting to our database and fixed it with a bit of hackery: dplyr hard codes the call to `RPostgreSQL::PostgreSQL()` without a max.con parameter being used, so I modified our installation as follows to increase the allowed connections. Note the `max.con` parameter is _not there_ in the _master_ branch:

```
src_postgres <- function(dbname = NULL, host = NULL, port = NULL, user = NULL,
                         password = NULL, max.con = 128 , ...) {
  if (!requireNamespace("RPostgreSQL", quietly = TRUE)) {
    stop("RPostgreSQL package required to connect to postgres db", call. = FALSE)
  }

  user <- user %||% if (in_travis()) "postgres" else ""

  con <- dbConnect(RPostgreSQL::PostgreSQL(max.con = max.con), host = host %||% "", dbname = dbname %||% "",
    user = user, password = password %||% "", port = port %||% "", ...)
  info <- dbGetInfo(con)

  src_sql("postgres", con,
    info = info, disco = db_disconnector(con, "postgres"))
}

```

However, now even with my modified dplyr code, I am hitting the limit again. When I try to set max.con in the call to dbPool, I get an unused argument error and it will not run.

### Runs:
```
pool_edna <- dbPool(
  drv = "PostgreSQL",
  host = db_host,
  dbname =   [working name],
  user = username
)
```

### Gives error:
```
pool_edna <- dbPool(
  drv = "PostgreSQL",
  host = db_host,
  dbname =   [working name],
  user = username,
  max.con = 64
)
```

**Comment by koseri** [comment]
BTW: Running out of connections happens not in the first session that I open, but in subsequent sessions.

**Comment by bborgesr** [comment]
Thanks for this. I'll take a look soon. I think the reason this is happening is because `pool` is not yet very well integrated with `dplyr`, so connections leak fairly often, leading to a build-up of connections. So the problem is not so much that the limit of connections is 16, but rather that connections are not getting recycled. Hadley is going to merge a PR into `dplyr` soon to make the integration between our two packages better, at which point the leaking shouldn't happen anymore. So, I'd prefer to wait until then and then revisit this, to see if the problem goes away or it persists.

I think that's the reason you don't run out of connection in the first session -- you haven't leaked the 16 connections yet, so you can just fetch a new one. A workaround until then is to open a new pool for each session, rather than using the same one across all sessions. However, this is not the way we'd envisioned `pool` would be used, so it's not really a solution in my view. I hope we can move forward, together with the `dplyr` package, into a real solution. Sorry about this! If you feel like this is urgent for you, let me know and I can see if there's another way around it...

**Comment by bborgesr** [comment]
As for your question of how you can use the `max.con` arg in `dbPool` (or DBI's `dbConnect`, for that matter), you can simply, specify it in the function call itself (in the `drv` arg), rather than manipulating `dplyr` or `pool` code (which actually turns out to be a lot cleaner for you). E.g. `drv = RPostgreSQL::PostgreSQL(max.con = 20)` as in:

```r
library(dplyr)
library(pool)
library(DBI)
library(RPostgreSQL)
library(shiny)

pool <- dbPool(
  drv = RPostgreSQL::PostgreSQL(max.con=20),
  dbname = "postgresdemo",
  host = "postgresdemo.cfd8mtk93q6a.us-west-2.rds.amazonaws.com",
  user = "guest",
  password = "guest"
)

ui <- fluidPage(
  actionButton("recalc1", "Re-query the database (1st table)"),
  tableOutput("tbl1")
)

server <- function(input, output, session) {
  output$tbl1 <- renderTable({
    n <- input$recalc1
    tbl <- src_pool(pool) %>% tbl("city") %>% head(n + 1) 
    print(dbGetInfo(pool)$numberTakenObjects)
    tbl
  })
}

shinyApp(ui, server)
```

**Comment by bborgesr** [comment]
Ok, I have just pushed some commits that will aggressively catch and destroy leaked connections, so you shouldn't experience a leaked connection build-up anymore (with the latest version of `pool`). Let me know if that continues to happen or if you encounter any other problems. As I mentioned above, this is just a workaround until `pool` and `dplyr` are better integrated and we can recycle leaked connections, instead of destroying them. However, this does not at all affect the code from the app author's perspective (you'll just have sub-optimal performance until then).
