### ISSUE TITLE
Need to implement own backend for Teradata in order to use src_pool(pool)?

### ISSUE THREAD

**Issue by happyshows** [rstudio/pool#28]
below pool object was identical to the config I used in #24 
```
src_pool(pool)

Error in UseMethod("src_desc") : 
  no applicable method for 'src_desc' applied to an object of class "c('src_', 'src_sql', 'src')"
In addition: Warning message:
In force(expr) : You have a leaked pooled object. Destroying it.
```

**Comment by bborgesr** [comment]
If you're using just DBI, that should work. However, `dplyr` only supports MySQL, SQLite and Postgres when it comes to RDBMSs (see [here](https://cran.r-project.org/web/packages/dplyr/vignettes/databases.html)). This may change in the future, hopefully! (see #20). But, for now, if you need to connect to Teradata, you should stick to the native `DBI` terminology, instead of `dplyr`'s.

**Comment by bborgesr** [comment]
Since dplyr 0.7.0 drops the use of `src_` completely, I don't think this is relevant anymore.
