### ISSUE TITLE
pool not function as intended in shiny mode - connection not being closed after shiny app closes

### ISSUE THREAD

**Issue by happyshows** [rstudio/pool#38]
I put the following chunk in global.R and observe the status of postgres on linux box.

pool <- dbPool(RPostgres::Postgres(),dbname = 'comment', 
 host = 'XX.XX.XX.XX', 
 port = 5432, 
 user = 'shiny',
 password = '****')

Each time when I launch a new shiny app instance, the connection (created in global.R) won't close even after shiny app has ended. I ran & closed 3 times of the shiny app which generates 19744, 19750 & 19833 idle threads.

During the app session, there's no more thread being created though, so it looks fine.

Is there any reason why the pool object & its connection are not destroyed after shiny app terminates?

├─19614 postgres: shiny comment XX.XX.XX.XX(63060) idle
 ├─19619 postgres: shiny comment XX.XX.XX.XX(63065) idle
 ├─19720 postgres: shiny comment XX.XX.XX.XX(63263) idle
 ├─19744 postgres: shiny comment XX.XX.XX.XX(57418) idle
 ├─19750 postgres: shiny comment XX.XX.XX.XX(57436) idle
 └─19833 postgres: shiny comment XX.XX.XX.XX(57564) idle

**Comment by sanjmeh** [comment]
same thing happens in MySQL

**Comment by bborgesr** [comment]
The most reliable way to ensure that this does not happen is to always call `poolClose(pool)` after you're done with your Pool object. If you're creating the app interactively on the console, you can just type that into the console directly after you close down the app. However, this is not a situation that scales at all to deployed apps. There's two possibilities for that:

- move your Pool object inside the server function use `session::onSessionEnded()` to call `poolClose(pool)` after the session is over. This is possible today, but not ideal since you usually want to share the Pool object between all your sessions.

- wait for rstudio/shiny#1770 to be implemented in Shiny: this will create a similar function, but that is global and not session-specific. This will be the recommended way to deal with `pool` in Shiny apps (since experience has taught us not to rely on finalizers...)

I hope that rstudio/shiny#1770 will move quickly since this is a priority for pool. This issue here has taken a dependency on it, so you'll be able to see it when that's merged.

**Comment by bborgesr** [comment]
> wait for rstudio/shiny#1770 to be implemented in Shiny: this will create a similar function, but that is global and not session-specific. This will be the recommended way to deal with pool in Shiny apps (since experience has taught us not to rely on finalizers...)

This has been on CRAN for a while now. From now on, shiny app authors should always close the pool themselves. This is how you do it:

```r
library(shiny)
library(pool)

pool <- dbPool(
  drv = RMySQL::MySQL(),
  dbname = "shinydemo",
  host = "shiny-demo.csa7qlmguqrf.us-east-1.rds.amazonaws.com",
  username = "guest",
  password = "guest"
)
onStop(function() {
  poolClose(pool)
})

shinyApp(ui, server)
```
