### ISSUE TITLE
Is it possible to connect to a MySQL database using pool from an RStudio instance on EC2?

### ISSUE THREAD

**Issue by ChadEfaw** [rstudio/pool#41]
All,

Thank you so much for your work with pool. 

I am interested in connecting to a MySQL database from an RStudio instance that is sitting on AWS/EC2. I have successfully been able to connect to that particular database from RStudio on my personal machine but am having issues when pasting that code into the EC2 RStudio instance. 

pool <- dbPool(
drv = RMySQL::MySQL(),
dbname = "my_database_name",
host = "my_database_host_name",
username = "my_username",
password = "my_password"
)

using this syntax, it works perfectly on my own computer but gives me the following error on the EC2 instance:

Error in connection_create(host, username, password, dbname, port, unix.socket,  : 
  Failed to connect: Can't connect to MySQL server on 'www.mywebsite.com' (110)

Any help is greatly appreciate and thanks again for all the work you do! 

Best,
Chad

**Comment by alandipert** [comment]
Hi @ChadEfaw, is the string `'www.mywebsite.com'` anywhere in your configuration?

I ask because it's definitely not an RDS host name 😃 

Another reason you might not be able to connect to RDS from your EC2 instance is, RDS might not be configured to allow connections from your EC2 instance. For details on how to accomplish this, you can check out http://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_VPC.Scenarios.html

Let me know if either of those observations are helpful.

**Comment by ChadEfaw** [comment]
Alan,

Thank you for taking the time to reach out to me! 

I definitely agree that the EC2 IP issue is probably the reason for the connection failure. I will test that and make sure to follow up.

Best,
Chad
