### ISSUE TITLE
object '20170621-043923.168669-110' not found

### ISSUE THREAD

**Issue by feilx** [rstudio/pool#43]
when used pool into ROracle, I found there was something wrong as follow:
simpleWarning in rm(list = tasks[[1]], envir = private$scheduledTasks): object '20170621-043923.168669-110' not found

**Comment by bborgesr** [comment]
Thanks for the report. I'm currently working on this package. Right now, I'm ensuring compatibility with the brand new `dbplyr` package. But this bug is next on my TODO list, since I think you're suffering from the same problem that is documented in #40. When I have a solution in place, I'll let you know.

**Comment by feilx** [comment]
Thank you for your reply.

**Comment by bborgesr** [comment]
Closed by #44. You should no longer see this problem. If anything seems off, let me know.
