### ISSUE TITLE
Pool and latest DBI (0.8)

### ISSUE THREAD

**Issue by StigKorsnes** [rstudio/pool#64]
### Example
`library(DBI)`
`library(pool)`
`library(config)`
`cfg=get()`
`dbPool<-dbPool(odbc::odbc(),.connection_string=cfg$DB$connectionStringTrusted)`
`  tblRead <- dbQuoteIdentifier(dbPool,Id(catalog="NBP_Production",schema="Data",table="FwdRates"))` 

Never mind the actual connection, but I get an error with "dbQuoteIdentifier". Use this code to handle schemas within MS Sql Server.

`Error in (function (classes, fdef, mtable)  : unable to find an inherited method for function ‘dbQuoteIdentifier’ for signature ‘"Pool", "Id"’ `

**Comment by bborgesr** [comment]
Yes, thank you for the report and I'm sorry for the trouble. Since DBI just went to CRAN with a couple of breaking changes, this package is now out of date and getting it submitted (and accepted) to CRAN is one of my priorities this week. I'll comment on this issue once the fix is on master and I've at least submitted to CRAN.

**Comment by bborgesr** [comment]
This should now be fixed in master and out on CRAN in a few days.

**Comment by bborgesr** [comment]
This is now on CRAN. @StigKorsnes, can you confirm you no longer experience that issue in your use case?

**Comment by StigKorsnes** [comment]
The snippet does indeed work now, @bborgesr . Perfect, thanks!
