### ISSUE TITLE
Convenience function: cleanup_pool

### ISSUE THREAD

**Issue by taqtiqa-mark** [rstudio/pool#66]
Maybe I'm doing it wrong, but I find myself writing this:

````r
cleanup_pool <- function(db_pool,conn){
  if(db_pool$valid){
      while(db_pool$counters$taken > 0) poolReturn(conn)
      poolClose(db_pool) # Close the DB pool
  }
}
````

This could be simplified if `conn <- poolCheckout(db_pool)` was given a pointer(`.Alias`?) to the `db_pool`.  then we could simplify and kill two birds with one stone with `cleanup_pool(conn)`

**Comment by lizard12995** [comment]
Hey there -- I've been struggling with trying to close the pool after checking out/ returning the object. once it's returned, it becomes a 'formal class pqconnection' and I can't use poolClose because "unable to find an inherited method for function 'poolClose' for signature '"PqConnection"'" -- does your function solve for this? I get the sense that that's what you're getting at..but I'm not certain. Also I realize you posted this a long time ago, soo apologies for dragging this up!

**Comment by taqtiqa-mark** [comment]
You'll have to try and inspect the runtime code - I haven't used this code in years so can't comment sensibly.

**Comment by hadley** [comment]
That seems like an anti-pattern as you should be closing as you go, not all at once at the end.
